### ISSUE TITLE
pgenv.sh missing

### ISSUE THREAD

**Issue by DaanVanVugt** [kartoza/docker-pg-backup#81]
Used in for example https://github.com/kartoza/docker-pg-backup/blob/master/scripts/restore.sh#L6

**Comment by andreimirt** [comment]
@NyakudyaA First. Thanks.
Second, most likely he tried to run it the same way I tried to do it.
I created a second container only for restoring, because I'm using a synology nas and I'd rather not ssh into it and run docker commands. In this second container I initially overrode the entrypoint to ```/backup-scripts/restore.sh```, so the pgenv.sh wasn't created.

The solution (thanks to your comment) is to override the entrypoint and leave it to just ```/bin/bash``` and then as command I used ```-c /backup-scripts/start.sh && /backup-scripts/restore.sh```
In this restore container, I'm using the exact same variables as in the backup container, but I also make use of the ```RUN_ONCE``` variable, and also of ```DUMPPREFIX``` to distinguish between regular backups and the "just before restoration" backups which are probably bad in some ways, hence the need of restoration, but they may still hold data that doesn't exist in the backup.
Everything seems to work just fine with a postgis container that is not the kartoza one.
